# coding: utf-8
LINKS = {
    "Git": "http://git-scm.com/", 
    "RoR": "http://rubyonrails.org/", 
    "Business Logic和Domain Logic的区别": "http://forums.puremvc.org/index.php?topic=1327.0", 
    "我的豆瓣": "http://www.douban.com/people/topman/", 
    "上文": "http://towerjoo.blog.techweb.com.cn/archives/99.html", 
    "Class-based generic views": "http://docs.djangoproject.com/en/dev/topics/class-based-views/", 
    "scp": "http://linux.about.com/od/commands/l/blcmdl1_scp.htm", 
    "笑傲江湖": "http://baike.baidu.com/view/10786.htm#2", 
    "PureMVC": "http://puremvc.org/", 
    "Quora": "http://www.quora.com", 
    "forms": "http://docs.djangoproject.com/en/dev/topics/forms/", 
    "智明星通": "http://elexhome.appspot.com/", 
    "Zynga": "http://www.zynga.com/", 
    "《做真正重要的事》": "http://www.mifengtd.cn/articles/how-to-focus-on-what-truly-matters.html", 
    "恺英网络": "http://www.kai-ying.com/", 
    "学习30个新单词": "http://www.mattcutts.com/blog/learn-30-new-words/", 
    "Github": "http://github.com", 
    "相关的教程": "http://darkstar.puremvc.org/content_header.html?url=http://puremvc.org/pages/docs/current/PureMVC_Implementation_Idioms_and_Best_Practices_cn.pdf&desc=PureMVC%20Docs:%20Best%20Practices%20and%20Implementation%20Idioms%20(Chinese%20Translation)", 
    "CC": "http://creativecommons.org/licenses/", 
    "Mercurial": "http://mercurial.selenic.com/", 
    "Gnome Do": "http://do.davebsd.com/", 
    "《如何利用期限来完成任务》": "http://www.mifengtd.cn/articles/budget-your-time-how-to-use-deadlines.html", 
    "Django": "http://djangoproject.com", 
    "Quicksilver": "http://en.wikipedia.org/wiki/Quicksilver_(software)", 
    "PureMVC教程": "http://darkstar.puremvc.org/content_header.html?url=http://puremvc.org/pages/docs/current/PureMVC_Implementation_Idioms_and_Best_Practices_cn.pdf&desc=PureMVC%20Docs:%20Best%20Practices%20and%20Implementation%20Idioms%20(Chinese%20Translation)", 
    "@towerjoo": "http://t.sina.com.cn/towerjoo", 
    "GLOSSARY OF ONLINE GAMES": "http://www.gamesbrief.com/2010/07/glossary-of-online-games/", 
    "Rubeus Hagrid": "http://en.wikipedia.org/wiki/Rubeus_Hagrid", 
    "Colibri": "http://colibri.leetspeak.org/", 
    "社交游戏": "http://towerjoo.blog.techweb.com.cn/social-game", 
    "文字内容": "https://github.com/topman/blog", 
    "小鞋匠": "http://baike.baidu.com/view/3319943.htm", 
    "@刘勇": "http://t.sina.com.cn/rekooliuyong", 
    "linkedin": "http://www.linkedin.com/", 
    "《防止拖延的积极步骤》": "http://www.mifengtd.cn/articles/steps_to_prevent_procrastination.html", 
    "Subversion": "http://subversion.tigris.org/", 
    "pureMVC": "http://puremvc.org/", 
    "database aggregation": "http://docs.djangoproject.com/en/dev/topics/db/aggregation/", 
    "完全用命令行工作-1\\": "拔掉你的鼠标:", 
    "@王玉辉": "http://t.sina.com.cn/1847100191", 
    "下载zip后的代码": "https://github.com/topman/blog_code/zipball/master", 
    "热酷": "http://rekoo.com/", 
    "wikipedia": "http://en.wikipedia.org/wiki/Side_effect_(computer_science)", 
    "一天拍一幅画": "http://www.mattcutts.com/blog/a-picture-a-day/", 
    "相关代码": "https://github.com/topman/blog_code", 
    "标题": "http://www.google.com.hk/search?hl=zh-CN&newwindow=1&safe=strict&q=quora+vs+stackoverflow&aq=f&aqi=&aql=&oq=", 
    "Bitbucket": "https://bitbucket.org/", 
    "Google Code": "http://code.google.com/projecthosting/", 
    "StackOverflow": "http://stackoverflow.com/", 
    "Rework": "http://37signals.com/rework/", 
    "本文中相关代码下载": "https://github.com/topman/blog_code/tree/master/HelloPureMVC", 
    "《一个月培养一个好习惯》": "http://www.mifengtd.cn/articles/culture-a-habit-in-a-month.html", 
    "sphinx": "http://sphinx.pocoo.org/", 
    "Matt Cutts": "http://www.mattcutts.com/blog/", 
    "你是我的兄弟": "http://baike.baidu.com/view/4605911.html", 
    "@我心_李力": "http://t.sina.com.cn/newleeli", 
    "《学会自律系列总结》": "http://www.mifengtd.cn/articles/self-discipline-summary.html", 
    "StackExchange": "http://stackexchange.com/", 
    "写一个小说": "http://www.mattcutts.com/blog/nanowrimo-write-a-novel/"
}
